# Generated by Django 3.1.7 on 2021-03-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percentageapp', '0002_auto_20210331_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('sid', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('sbranch', models.CharField(max_length=30)),
                ('telugu', models.IntegerField(max_length=3)),
                ('hindi', models.IntegerField(max_length=3)),
                ('english', models.IntegerField(max_length=3)),
                ('mathes', models.IntegerField(max_length=3)),
                ('science', models.IntegerField(max_length=3)),
                ('social', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Student1',
        ),
    ]
