# Generated by Django 3.1.4 on 2021-03-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percentageapp', '0004_auto_20210331_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student4',
            fields=[
                ('sid', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('sbranch', models.CharField(max_length=30)),
                ('telugu', models.IntegerField(max_length=3)),
                ('hindi', models.IntegerField(max_length=3)),
                ('english', models.IntegerField(max_length=3)),
                ('mathes', models.IntegerField(max_length=3)),
                ('science', models.IntegerField(max_length=3)),
                ('social', models.IntegerField(max_length=3)),
                ('total', models.IntegerField(max_length=5)),
                ('sperc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Student3',
        ),
    ]
